### ISSUE TITLE
null given when starting a workflow

### ISSUE THREAD

**Issue by MCKLtech** [42coders/workflows#22]
I've set up a basic observer workflow on the User model to trigger when it is updating. I trigger the update by modifying in Nova, similar to the demo video in the README.

It seems in the start() method of the Trigger, the $this->workflow variable is null:

```
the42coders\Workflows\Triggers;

$log = WorkflowLog::createHelper($this->workflow, $model, $this);
```

Digging into the database, it seems the trigger is referencing the wrong workflow_id (In my case, it was referencing a deleted Workflow (ID: 3) when it should have been referencing the only Workflow in the system (ID: 6) Therefore, this worked:

`$log = WorkflowLog::createHelper(Workflow::find(6), $model, $this);`

And the queue ran as expected.

My assumption is that the Workflow model needs a cascading delete?

**Comment by Max-Hutschenreiter** [comment]
Fixed with 0.0.12 (new composer relation added to the package)
