### ISSUE TITLE
Unable to Install with php 8.0 and laravel 9 framework

### ISSUE THREAD

**Issue by ershadow786** [42coders/workflows#26]
This is my composer.json 

> {
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/fortify": "^1.11",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "owen-it/laravel-auditing": "^12.2",
        "realrashid/sweet-alert": "^5.0",
        "santigarcor/laratrust": "^7.0",
        "spatie/laravel-permission": "^5.5",
        "symfony/event-dispatcher-contracts": "^2.4",
        "yajra/laravel-datatables-oracle": "~9.0",
        "zerodahero/laravel-workflow": "^4.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

but when  i install the42coders/workflows it give me error 

> Problem 1
    - barryvdh/laravel-dompdf v0.9.0 requires illuminate/support ^5.5|^6|^7|^8 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - the42coders/workflows 0.0.12 requires barryvdh/laravel-dompdf ^0.9.0 -> satisfiable by barryvdh/laravel-dompdf[v0.9.0].
    - Root composer.json requires the42coders/workflows ^0.0.12 -> satisfiable by the42coders/workflows[0.0.12].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require the42coders/workflows:*" to figure out if any version is installable, or "composer require the42coders/workflows:^2.1" if you know which you need

**Comment by ershadow786** [comment]
I Don't why there is conflict with illuminate/support ?

**Comment by Max-Hutschenreiter** [comment]
I will have a look

**Comment by ershadow786** [comment]
very good library ,using it personal project for now i have downgraded PHP and laravel version.
