### ISSUE TITLE
Parallel execution?

### ISSUE THREAD

**Issue by viezel** [42coders/workflows#3]
Interesting package. 

Lets say I want to implement multi-approver to a Blog Post. Where I need them to run it parallel. Then the flow will look something like this:

![multi-approver](https://user-images.githubusercontent.com/312065/97302097-e1d5b580-1858-11eb-8cc2-019af8d474c0.png)

Would it be possible to use a parallel execution in this package? (called Parallel Gateway in [BPMN 2.0 spec](http://www.bpmn.org/))

if not, any plans to support it? 

Cheers

**Comment by Max-Hutschenreiter** [comment]
Hey, thanks for your interest in the Package.

Thirst thing the Package is not really BPMN compatible :( I thought a lot about it but to make it easier to use I decided to keep it simpler. 

The aspects I want to include are 
- Async Flow of the Workflow means that a Workflow can be interrupted for a User input and then continue.
- The Exclusive Gateways are one of the next things I am planning to do. 


Actually, there are not so many things missing from your workflow if you would split it into multiple workflows. 
1. Workflow sends the approval mail to the two recipients. The mail contains two links for acceptance and rejection.
2. We would need one more trigger for webhooks (is coming soon) Which is starting the rejecting or the approve Workflow.

If you have any hurdles in using the Package feel free to contact me by mail I am happy to help.

**Comment by viezel** [comment]
Thanks for the answer Max.

Interesting that you evaluated BPMN and turned another direction. Understand it in terms of simplicity.

Regarding multiple workflows, that's not really an option. Now imagine the approval flow is much larger, 5, then 5, then 3 approvers. Now it could be split up, then then you lose all the progression, and when to notify all participants if anyone rejects. 


Do you have plans to support parallel? 

Regarding any hurdles. I think the biggest is how you have bundled everything together. core logic, jQuery, css, views, webpack config etc. Many developers use different tech stacks and would like only the core features. 

I would suggest to split it into different packages:

- Workflow-Core
- Workflow-UI
