### ISSUE TITLE
setting workflow.prefix leads to two occurances

### ISSUE THREAD

**Issue by hikoukinin** [42coders/workflows#31]
I have installed in a Laravel 9 environment that has a path 'domain/crm' that redirects to 'domain/crm/admin' once authenticated. I can launch the 'index.blade' as domain/crm/admin/workflows, and the URL for the CREATE button is domain/create. If I set the prefix value in config/workflow.php to admin, the URL for the CREATE button is now domain/crm/admin/admin/create.

What I have found, if I set the prefix value in config/workflow.php the domain and path (i.e. domain/crm) is added as a prefix as well as the config/workflow.php value as the URL, however if the is no config/workflow.php value then only the domain is added as a prefix.

Workaround is to replace blade occurances of  {{  config(workflows,prefix) }} with {{ url ('/') }} in the blade files.

**Comment by Max-Hutschenreiter** [comment]
I am sorry there is a bug with the prefixes I will fix it today and make a new release.

**Comment by Max-Hutschenreiter** [comment]
Fix in version 0.0.14 can you please check?

**Comment by hikoukinin** [comment]
I did a clean install with PHP 8.0.22 and Laravel 9.19.0.

create.blade.php line 13 is missing ")" after ['workflow' => $workflow]. After I correct get "Undefined variable $workflow".

**Comment by hikoukinin** [comment]
I did a clean install with PHP 8.0.22 and Laravel 9.19.0.

 

create.blade.php line 13 syntax error, seems to be missing a ")".

 

index.blade.php and diagram.blade.php - awesome font icons not displaying (404 errors - ***@***.***/fontawesome-free/webfa-solid-900.ttf?781e85bb50c8e8301c30de56b31b1f04) domain/public not domain/path/public.

 

diagram.blade.php - 403 error for addTrigger (workflow.js)

**Comment by Max-Hutschenreiter** [comment]
Sorry I published a new fix and also fixed the tests :(
