### ISSUE TITLE
Individual Item Workflows?

### ISSUE THREAD

**Issue by TonyPartridgeR** [42coders/workflows#37]
We are looking at building a form submission system, whereby it can have several steps (Workflow) and then going through a set of steps dependent on the values entered. 

Is this possible within this package? From what I can see, it only applies to whole models without individualization to the model items.

**Comment by Max-Hutschenreiter** [comment]
It's not possible in the current state. You can change the model along the Workflow. But it has no functionality for requesting user input between the steps.
