### ISSUE TITLE
SaveFile missing

### ISSUE THREAD

**Issue by manikandanocs** [42coders/workflows#41]
Unable to find SaveFile task classes. Or can you tell me , how to save the generated PDF file using DOMPDF task?

**Comment by Max-Hutschenreiter** [comment]
Hey @manikandanocs, at the moment, there is no task for it. Since I only used it to send the pdfs per mail. But you can create your own Tasks inside your project and register them in the config.

**Comment by manikandanocs** [comment]
Yes, I have created a task for it myself.  Little bit confused by seeing your documentation

**Comment by Max-Hutschenreiter** [comment]
If you have an idea to improve the Documentation, feel free to make a pull request. Same for the SaveFile Task, it would be nice to have it in the Package.
