### ISSUE TITLE
Conditions stoped working

### ISSUE THREAD

**Issue by tarkabuka** [42coders/workflows#42]
In the workflows no matter if the field is a string or int the condition is never executed correctly equal or not_equal.

example:
The Condition for Task TextInput with the field AppModelsasset-&gt;statsInt equal 2 failed.

The Condition for Task TextInput with the field AppModelsasset-&gt;status equal Assign failed.

Tried several conditions and result is always the same.

i'm using a condition HTML_IMPUT, didn't work, also test the condition on send email with the same result

**Comment by Max-Hutschenreiter** [comment]
I will have a look

**Comment by Max-Hutschenreiter** [comment]
Fixed in the new release 0.0.19
